title: Illinois CS Proficiency Exams
description: >- # this means to ignore newlines until "baseurl:"
  Information about CS@Illinois proficiency exams
url: https://proficiency.cs.illinois.edu/
repository: "texne/proficiency.cs.illinois.edu"
exams:
  - 101
  - 105
  - 124
  - 125
  - 128
  - 173
  - 225
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_bootstrap.sh
  - courses
  - Rakefile
  - README.md
  - package-lock.json
  - vendor
markdown: kramdown
kramdown:
  auto_ids: false
